### ISSUE TITLE
Links within the page not working properly 

### ISSUE THREAD

**Issue by pgyogesh** [jarrekk/Jalpc#101]
Looks like links are not working properly with kramdown engine. Whenever I click on any link the page is going little down.

Example [link](http://www.pgyogesh.com/gpdb/2017/12/06/important-gpdb-sqls.html)

But it works perfectly in ![here](https://github.com/pgyogesh/pgyogesh.github.io/blob/master/_posts/2017-12-06-important-gpdb-sqls.md)

**Comment by vedantpuri** [comment]
If this refers to the sections on the page such as skills, careers project, I am also facing a similar issue because when I click on skills it scrolls down alot, so much so that 'My Skills' and a part of the skill web goes out of frame sometimes. Same goes for going in the upward direction
