### ISSUE TITLE
better mobile support with metatag

### ISSUE THREAD

**Issue by fossedihelm** [jarrekk/Jalpc#104]
Putting
 `<meta name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1; minimum-scale=1; user-scalable=no;" />` 
instead of 
`<meta name="viewport" content="width=device-width, initial-scale=1">` will fix a bug in mobile version.
In my case without scale will produce [this effect](https://github.com/fossedihelm/fossedihelm.github.io/blob/master/without%20scale.gif). Adding scale information will fix.

**Comment by jarrekk** [comment]
@fossedihelm Thanks, updated.
