### ISSUE TITLE
Different default language when i18n is enabled

### ISSUE THREAD

**Issue by Skyflash** [jarrekk/Jalpc#109]
Hi,
how i can set a default language different than en when i18n is enabled?

**Comment by jarrekk** [comment]
@Skyflash The wiki page [step 4](https://github.com/jarrekk/Jalpc/wiki/Multilingual-Page#step-4) has a code block on how to set default language.

**Comment by Skyflash** [comment]
Yes, i changed it. But it seems it doesn't work :(
My mistake?

**Comment by jarrekk** [comment]
Have you updated the JSON file name in step 2?

**Comment by jarrekk** [comment]
You can show me your repo. :)

**Comment by Skyflash** [comment]
Ok, thank you :)

https://github.com/Skyflash/Jalpc

absolutely work in progress :)

**Comment by jarrekk** [comment]
@Skyflash I had a look at your repo, it's cool, perhaps this [doc](https://github.com/jarrekk/Jalpc#compress-css-and-js-files) can help you, the file you edit is not which used at Jekyll, you should compress it, then it should work.
Here is an issue about this: https://github.com/jarrekk/Jalpc/issues/64, needs improvement. :)

**Comment by Skyflash** [comment]
Ok, done following you [linked doc](https://github.com/jarrekk/Jalpc#compress-css-and-js-files)

1. run npm install -g uglifyjs
2. run npm install -g clean-css
3. run npm install (al three in the root of the project)
4. config localization.js (located in /static/asset/js/)
5. npm run build

Thank you ;)
