### ISSUE TITLE
baseurl: / does not work

### ISSUE THREAD

**Issue by kerner1000** [jarrekk/Jalpc#120]
I do not have a special base URL. If I change it to `baseurl: /` page is not rendered properly.

**Comment by Skyflash** [comment]
In my config.yml the baseurl is 
`baseurl:  ''`

**Comment by kerner1000** [comment]
Thanks, that works!

**Comment by jarrekk** [comment]
@kerner1000 No slash for no URI, thanks! @Skyflash
