### ISSUE TITLE
Carousel indicators not centered

### ISSUE THREAD

**Issue by dblessing** [jarrekk/Jalpc#51]
The carousel indicators have 60px right padding which puts them off-center. If the padding is removed they center correctly. 

**Current:**

<img width="820" alt="screen shot 2017-02-11 at 8 15 07 pm" src="https://cloud.githubusercontent.com/assets/2394772/22859095/e16b679a-f096-11e6-994e-186d463f2164.png">

**With padding removed:**

<img width="716" alt="screen shot 2017-02-11 at 8 15 14 pm" src="https://cloud.githubusercontent.com/assets/2394772/22859096/e25ad000-f096-11e6-9798-665ad898a07d.png">

**Comment by jarrekk** [comment]
@dblessing thanks for this issue,I have edit it at latest commit.👍
