### ISSUE TITLE
Is there some original sass source that is not open-sourced here?

### ISSUE THREAD

**Issue by chen-yumin** [jarrekk/Jalpc#52]
Thanks for this great theme. 

I just had a look at the [style.css](https://github.com/jarrekk/Jalpc/blob/master/static/css/style.css) file, and I find it hard to believe that a css styling file with more than 8000 lines code with zero comments is something that a developer could be working on. Is there some original sass source that is not open-sourced here? If so, how can we get them?

**Comment by jarrekk** [comment]
@CharmySoft 

Yes, this file is which I wrote with my colleagues at company,  later I will remove unused code and update it at this repo, thanks for pointing out this issue!

**Comment by jarrekk** [comment]
@chen-yumin 

I added a [script](https://github.com/jarrekk/Jalpc/blob/master/build/purify-css.js) that can purify style.css to [style-purify.css]https://github.com/jarrekk/Jalpc/blob/master/static/css/style-purify.css, you can see this file if you want to edit pages' style.
