### ISSUE TITLE
How to generate static/assets/app-20170226.min.css file

### ISSUE THREAD

**Issue by sheilazhang** [jarrekk/Jalpc#54]
Hello jarrekk : 

I want to know why there is a ```app-20170226.min.css``` named by time in ```static/assets/``` files. 
I want to modify some class, but it is a compressed file. can you tell me how to generate this file？

Thanks

**Comment by jarrekk** [comment]
Please see [README](https://github.com/jarrekk/Jalpc#compress-css-js), thanks.
