### ISSUE TITLE
Misdirected link on jekyllthemes.org

### ISSUE THREAD

**Issue by crichID** [jarrekk/Jalpc#59]
FYI, the link to your Demo on jekyllthemes.org is pointing to `http://www.jack003.com/` instead of `https://jarrekk.github.io/Jalpc/`. I thought you might want to know so you can fix it :wink:

**Comment by jarrekk** [comment]
Thanks for this issue! I have a [PR](https://github.com/mattvh/jekyllthemes/pull/430/files) at [jekyllthemes.org](https://github.com/mattvh/jekyllthemes), but this repo's owner wasn't online until now.
