### ISSUE TITLE
Links detected as ads by Adguard Adblocker

### ISSUE THREAD

**Issue by pegasusearl** [jarrekk/Jalpc#62]
Apparently the social links, and links in the footer with blue circle button detected as ads and hidden by [Adguard Adblocker](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg).

```
  <ul class="list-inline social-icon">
```

also I found these in the _includes/head.html : 
```
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-6196184668650108",
      enable_page_level_ads: true
    });
  </script>
```
Was it to show up ads? Where? I can't see any ads even if I disable adblock.

**Comment by jarrekk** [comment]
Thanks for this issue!
I wanted to add this ad to my own [website](http://www.jarrekk.com) and now I remove it at new [commit](https://github.com/jarrekk/Jalpc/commit/a93b202ee3d086793bdb5a715245f27fb461871b).
Hope you like this Jekyll theme.
