### ISSUE TITLE
Public API key for Disqus comments

### ISSUE THREAD

**Issue by MaxBenChrist** [jarrekk/Jalpc#65]
Hi there,

first, thank you for the great theme. 

I am struggling to setup the disqus comments. To get a public API key one has to register the application

https://help.disqus.com/customer/portal/articles/787016-how-to-create-an-api-application

is that really necessary?

On the disqus page under installation, one can find their https://help.disqus.com/customer/en/portal/articles/472097-universal-embed-code

which does not need an API key. It works with only `this.page.identifier`, `forum shortname` and `this.page.url`.

So what do you recommend? Should I register the application and get an API key or can we get the universal embed code into the Jalpc theme?

**Comment by felansu** [comment]
Hi @MaxBenChrist, in foot.html file you can see a js function doing request to https://disqus.com/api/3.0/threads/set.jsonp.
In disqus can read:
> Append #disqus_thread to the href attribute in your links. This will tell Disqus which links to look up and return the comment count. For example: <a href="http://foo.com/bar.html#disqus_thread">Link</a>.

i'm thinking how improve this.

**Comment by MaxBenChrist** [comment]
Hi @felansu, Thank you for the quick answer. 

Unfortunately, I suck at js, but if I can help you somehow, let me know.

**Comment by felansu** [comment]
@MaxBenChrist, here is working only putting yout Disqus name and comment all code in foot.html, only need this:

`{% include analytics.html %}`
 
I don't know what this code do (not necessary for my opinion):
```

{% include analytics.html %}

{% if site.disqus %}
  <script id="dsq-count-scr" src="//jalpc.disqus.com/count.js" async></script>
  <script type="text/javascript">
    var disqusShortName = "{{ site.disqus.name }}";

    var disqusPublicKey = "{{ site.disqus.public_key }}";

    var urlArray = [];
    $('.disqus-comment-count').each(function () {
      var url = $(this).attr('data-disqus-url');
      urlArray.push('link:' + url);
    });
    $.ajax({
      type: 'GET',
      url: "https://disqus.com/api/3.0/threads/set.jsonp",
      data: { api_key: disqusPublicKey, forum : disqusShortName, thread : urlArray },
      cache: false,
      dataType: "jsonp",
      success: function (result) {
        for (var i in result.response) {
          var count = result.response[i].posts;
          if ( count ) {
            $('.disqus-comment-count[data-disqus-url="' + result.response[i].link + '"]').html(count);
          }
        }
      }
    });
</script>
{% endif %}

```

**Comment by MaxBenChrist** [comment]
Well, that was a quick fix. Thanks @felansu

**Comment by jarrekk** [comment]
@MaxBenChrist I browsed <https://disqus.com> just now, found there were some changes in configuration of comment, now it doesn't need * public key*, but you still need to register and [add disqus to site](https://disqus.com/admin/create/), now this configuration is easier, I recommend you to use new method, later I will change Jalpc's config to this. Thanks!

@felansu code about disqus is in **_includes/foot.html**, **_includes/analytics.html** is website analytics code, the other code in **foot.html** is old way of get article's comment count, since article's comment count's config is easier as you mentioned, I will change config to this one in Jalpc. Thanks!

**Comment by MaxBenChrist** [comment]
@jarrekk Thx
