### ISSUE TITLE
carousel image can't display

### ISSUE THREAD

**Issue by hjfzxc** [jarrekk/Jalpc#69]
first push to GitHub, the carousel image don't display.   
where to modify so that the 'head_one and two' picture can display

**Comment by felansu** [comment]
@hjfzxc, you don't have commit the static/img/ folder and in your code are commented.

![screenshot from 2017-07-26 10-32-39](https://user-images.githubusercontent.com/1687697/28623942-dac479c6-71ed-11e7-8cf0-58811c070be9.png)

**Comment by felansu** [comment]
This resolve your problem https://github.com/hjfzxc/hjfzxc.github.io/pull/1

**Comment by hjfzxc** [comment]
Thanks a lot! It works well now.  Thank you  again for taking time to fix my problem

**Comment by felansu** [comment]
@hjfzxc, pleased close this issue :smile:
