### ISSUE TITLE
My CSS are all hung up

### ISSUE THREAD

**Issue by BillEliot** [jarrekk/Jalpc#70]
Hello, I had Forked your blog long ago。
But,a few days ago,I found my blog's css are all hung up!!!!!!!
404! 404! a lot of 404s!!!

The github's update has limited something? So I had so many 404s?

please help me!
thank you!

**Comment by felansu** [comment]
Run:
`npm run build` and push all files.

**Comment by BillEliot** [comment]
oh..

sorry
I can't understand, Did you know how did this problem come about?

**Comment by BillEliot** [comment]
Oh
I had resolved my problem 
I think GitHub maybe update

**Comment by jarrekk** [comment]
Thanks :) @felansu
