### ISSUE TITLE
CSS unused

### ISSUE THREAD

**Issue by felansu** [jarrekk/Jalpc#71]
I think the style.css file has a lot of CSS without being used.

For example:

```
table.shoping-cart-table tr td.desc,
table.shoping-cart-table tr td:first-child {
    text-align: left
}

table.shoping-cart-table tr td:last-child {
    width: 80px
}

.product-name {
    font-size: 16px;
    font-weight: 600;
    color: #676a6c;
    margin: 2px 0 5px
}

.product-name:focus,
.product-name:hover {
    color: #3385FF
}

.product-price {
    font-size: 14px;
    font-weight: 600;
    color: #fff;
    background-color: #3385FF;
    padding: 6px 12px;
    position: absolute;
    top: -32px;
    right: 0
}

.product-detail .ibox-content {
    padding: 30px 30px 50px
}

```

This are used ?

`body.rtls` are used ? Because from line 7921 to 8177 rtls is being used.

I need to know this for refactoring to minimalist and performative css code.

**Comment by jarrekk** [comment]
@felansu You are right, they are not used for this site, of course you can remove it.  **style.css** is a file which I used for many websites, I use [purifycss](https://github.com/purifycss/purifycss) to remove unused css code and you can refactor this file with this package, it's the laziest way to reuse code :)

**Comment by felansu** [comment]
@jarrekk ohh sorry, I did not know purifycss ! Thanks !
