### ISSUE TITLE
pace-progress

### ISSUE THREAD

**Issue by felansu** [jarrekk/Jalpc#72]
jalpc have pace-progress js injected but not your css, see files.conf.js

can remove this package ?

**Comment by jarrekk** [comment]
Thanks a lot for reminding this feature, I forgot adding pace css file, so we can't see pace animation when we open pages. Later I will fix it in a new commit.

**Comment by felansu** [comment]
Now pace-progress are running !

**Comment by jarrekk** [comment]
Yep, thanks! :)
