### ISSUE TITLE
How do I change the initial color of the nav bar menu? 

### ISSUE THREAD

**Issue by nelsonmestevao** [jarrekk/Jalpc#75]
The initial color is white and when I scroll down it became gray. How do I keep the color text gray the whole time?

I get confuse with the css and sass files...

If you could help me I would be thankful!

**Comment by jarrekk** [comment]
Thanks for using this theme, anyone who wants to change color in this theme may be a little confused, later I will try to make these color as variables :)

You can find CSS code of nav bar color with Chrome inspect:
![7207488e-6208-490d-bb55-a6ca959d6d33](https://user-images.githubusercontent.com/10969478/28753440-2d50f80a-7567-11e7-8790-8430b1d8ca82.jpeg)
and the code is at file **static/css/style-purify.css** line 2222, after you change it, you should compress CSS file with command `npm run build`, thanks!

**Comment by nelsonmestevao** [comment]
Thank you for this theme!

If you could put it as variables would be great!

Thank you for the help, however at `style-purify.css` line 2222 theres nothing like that..

**Comment by jarrekk** [comment]
You can search word `.landing-page .navbar-default.navbar-scroll` at file **style-purify.css**
In Jalpc it locates at [here](https://github.com/jarrekk/Jalpc/blob/master/static/css/style-purify.css#L2222-L2226)

**Comment by AhmetBas** [comment]
Hi in my setup i have to edit /static/assets/app-20170729.min.css. Is there an reason why i have to edit /static/assets/app-20170729.min.css for changing my colors.

**Comment by jarrekk** [comment]
@AhmetBas  It's not advisable to edit **app-xxx.min.css** file because it's a compressed file. Please edit **style-purify.css**.

**Comment by AhmetBas** [comment]
@jarrekk Okay, i am not an very familiar with front end what happens if i use the compressed file. Could you also explain which i have to edit of the css since i have static file outsite my _site and an static file inside my _side.  Its confusing me

**Comment by jarrekk** [comment]
@AhmetBas Advice you to read documents about [Jekyll](https://jekyllrb.com/), this issue isn't about its original motif, so it will be closed.
