### ISSUE TITLE
Not getting blog posts in website.

### ISSUE THREAD

**Issue by pgyogesh** [jarrekk/Jalpc#78]
Hi Jarrekk,

Hope you are doing good!

Although I have created .md file in `_posts` directory, post is not displayed at blog page

Thanks,
Yogesh

**Comment by jarrekk** [comment]
@pgyogesh You need to change filename like **date-xxx.md**.

**Comment by pgyogesh** [comment]
@jarrekk Thank You for your response. I renamed the .md file in *date-xxx.md* format but still no luck.

Even I copied your *2017-01-31-3-steps-to-setup-website-with-Jalpc.md.*

Thanks,
Yogesh

**Comment by jarrekk** [comment]
Please check your repo's branch is right.

**Comment by pgyogesh** [comment]
Got it... Thank you so much...
