### ISSUE TITLE
CSS doesn't load!!

### ISSUE THREAD

**Issue by ilyeSudo** [jarrekk/Jalpc#81]
hey, I've followed your documentation on how to setup the blog, but I run into this bug where css doesn't load! thanks in advance
![image](https://user-images.githubusercontent.com/16365985/29239778-c23f290c-7f56-11e7-80d4-7d90af39427b.png)

**Comment by jarrekk** [comment]
Please give me your website address

**Comment by AhmetBas** [comment]
@ilyeSudo @jarrekk this happens when your uploading the files into your own webserver with jekyll.

**Comment by ilyeSudo** [comment]
@jarrekk here's the repo https://github.com/ilyeSudo/ilyes 
and here's the blog https://ilyesudo.github.io/ilyes/

**Comment by jarrekk** [comment]
You need to edit [_config.yml](https://github.com/ilyeSudo/ilyes/blob/master/_config.yml#L4-L10).

**Comment by ilyeSudo** [comment]
@jarrekk I did!! can you have a look now, please? I didn't edit it all but, it should work!

**Comment by jarrekk** [comment]
Please make sure you edit file in correct branch.
