### ISSUE TITLE
ERROR: 'static/assets/static/css' not found

### ISSUE THREAD

**Issue by rosscyoga** [jarrekk/Jalpc#86]
Not sure why...but I'm getting a missing file error. I've spent the better part of a day looking for the error to no avail. There's no place this exact string occurs. It appears to be a parsing error somewhere in the build when a file path to a css file is being called from the script. Obviously, somewhere there is a load of css with a prepend 'static/assets/' calling a file from 'static/css', which of course is a false path.

Inspector Console refers to:
(index):488 and...
GET http://localhost:4000/static/assets/static/css 404 (Not Found) | app-20170904.min.js:4

Line 488 in index is for disqus
I commented that line out but doesn't help

Please advise.

**Comment by jarrekk** [comment]
Can you show me your website and code?

**Comment by academyyyy12** [comment]
i am not akses eror code..you can send project to i


2017-09-05 11:04 GMT+07:00 jarrekk <notifications@github.com>:

**Comment by rosscyoga** [comment]
https://github.com/rosscyoga/rosscyoga.github.io

Repo link to files/code

**Comment by jarrekk** [comment]
@rosscyoga I found this error at localhost, it shows 
![image](https://user-images.githubusercontent.com/10969478/30257498-2522e57c-96e5-11e7-9b1d-b00128afa9be.png)
and js file detail is 
![image](https://user-images.githubusercontent.com/10969478/30257490-18934e0a-96e5-11e7-9522-e6e26bf6c645.png)
these are some cod**bootstrap.js**, maybe there is something error during compress or your new js files have conflicts with **bootstrap.js**.

**Comment by rosscyoga** [comment]
Found it. It was buried in custom.css in an empty background: url(""); attribute...DOH!
