### ISSUE TITLE
Font size of blog posts 

### ISSUE THREAD

**Issue by ashutoshmjain** [jarrekk/Jalpc#87]
Jack - Hope you are doing well . 

I was wondering if there is an easy way to increase the font size of blog posts. It could be my older eyes :-) but I think its too small for good readability 

I am okay if the setting increases the font size across whole website . Even better . 

Cheers

**Comment by jarrekk** [comment]
@ashutoshmjain  Long time no see :)
When I design this theme I didn't take blog font size into consideration, but it's not easy for you to read, so I found an open source solution: [Markdown CSS](https://github.com/markdowncss). But it needs some edit before we use it. For changing font size I have the following code for reference:

```
.article p {
  font-size: 1.3em;
  margin-bottom: 1.3rem;
}

.article li {
  font-size: 1.3em;
}

.article code {
  font-size: 1.3em;
}

.article h1,
.article h2,
.article h3,
.article h4 {
  margin: 1.414rem 0 .5rem;
  font-weight: inherit;
  line-height: 1.42;
}

.article h1 {
  margin-top: 0;
  font-size: 4.398rem;
}

.article h2 {
  font-size: 3.11rem;
}

.article h3 {
  font-size: 2.199rem;
}

.article h4 {
  font-size: 1.555rem;
}

.article h5 {
  font-size: 1.233rem;
}

.article h6 {
  font-size: .968rem;
}

.article small {
  font-size: .778em;
}
```
You can create a file ***static/css/blog.css**, and link it at **_layouts/post.html** line 4. If the font size is not satisfied, you can change it.

**Comment by ashutoshmjain** [comment]
Wow  .. It worked like a charm  .. Many thanks .
