### ISSUE TITLE
The landing page pictures

### ISSUE THREAD

**Issue by ashutoshmjain** [jarrekk/Jalpc#89]
Jack 

You know there are two large pictures right on the top of landing page that continue on every screen.  In your website its the picture of a skateboard .. 

I feel these pictures are eating away lot of screen real estate , without carrying any specific meaning. Another problem is they don't look good on the smartphones .. 

Is there a way to remove these pictures for good  .. 

Btw  - thanks again for your help on the font sizes and the sample css you provided. I have made some modifications and now posts are looking really good .. 

Again - no hurry , please provide answer at your convenience 

Cheers

**Comment by jarrekk** [comment]
@ashutoshmjain 
This idea is very practical, landing pictures may give others the state of blog's owner, but if we see them too often, it's meanless.
In Jalpc, I added this [feature](https://github.com/jarrekk/Jalpc/blob/master/_config.yml#L53-L55) to open/close carousel with @felansu 's  PR, thanks.
If you want to edit the code of your blog, they are located at two files: [one](https://github.com/ashutoshmjain/homepage/blob/gh-pages/index.html#L46-L80), [two](https://github.com/ashutoshmjain/homepage/blob/gh-pages/_includes/header.html#L42-L77). 
Comment them can remove carousel.

**Comment by ashutoshmjain** [comment]
Jack - Thanks for the response. I removed the code. Its working well for the blog but somehow the homepage is NOT loading  .. 

https://ashutoshmjain.github.io/homepage/blog/  -- is good . this is exactly what I wanted 
https://ashutoshmjain.github.io/homepage/    -- NOTHING SHOWS up here . It is the main page.

**Comment by ashutoshmjain** [comment]
Again - No hurry as no one is anyway looking at my homepage  :-) .

**Comment by ashutoshmjain** [comment]
Jack 

I figured out the problem .. looks like I had deleted more lines in index.html  .. 

Everything good now and its looking beautiful 

Thanks again
