### ISSUE TITLE
Markdown code snippet "disappear" (collapse) unexpectedly upon clicking

### ISSUE THREAD

**Issue by Atlas7** [jarrekk/Jalpc#97]
For some reason, if you have a blog post with a markdown code snippet (created using the triple backtick method), and when you click on that code snippet, it for some reason "disappear" ( (or "collapse" in CSS terms)

[Here is a demo](https://atlas7.github.io/html/2017/11/23/code-snippet-test-2.html) - try click on the code snippet and you will see. [This is my GitHub repo](https://github.com/Atlas7/atlas7.github.io)

I've also just git clone the Jalpc repository from scratch, create a blog post (with a code snippet). Same outcome.

Anybody have similar issue / know how to solve this? (I have no idea how to solve this currently and am quite stuck!)

**Comment by Atlas7** [comment]
With the help of @keram [https://github.com/keram](https://github.com/keram) we've hunted down the bug.

Line 6-10 of the [this js file](https://github.com/jarrekk/Jalpc/blob/master/static/js/js.js#L6-L10) needs commented out / removed.

In addition, for the time being I manually remove the corresponding lines in the min files [here](https://github.com/jarrekk/Jalpc/tree/master/static/assets). i.e. `blog-20170906.min.js`.

**Comment by jarrekk** [comment]
@Atlas7 
Thanks for this issue and tracking bug with @keram !
It's fine to create a PR for this issue, nice job! :)

**Comment by Atlas7** [comment]
ah apologies for the delay on this (and I'm glad you've got it fixed nevertheless). Thank you!

**Comment by Atlas7** [comment]
Re-opening this thread. Turns out the minified javascript needs updating too. See [commit](https://github.com/jarrekk/Jalpc/pull/102).
