### ISSUE TITLE
mfizz icon mismatch?

### ISSUE THREAD

**Issue by kenaycock** [jarrekk/Jalpc#98]
The icon mapping seems to be mixed up in the latest version.

For instance, `icon-python` is the WordPress icon, and `icon-microscope` is a telephone. 

Is there an easy way to correct this?

**Update:** The mapping seems to be shifted by 20-some places; anyway, I figured out a workaround for the icon I was looking for (`icon-python` can be produced by referencing `icon-netbsd`)

**Comment by academyyyy12** [comment]
apa yang di rubah lgi jarrect


2017-11-29 12:58 GMT+07:00 Kenneth Aycock <notifications@github.com>:

**Comment by jarrekk** [comment]
@kenaycock Thanks!
bug fix now, please try new [commit](https://github.com/jarrekk/Jalpc/commit/3e5b21ed925b37386d3d185b0b0855cabac93efc).
